# Generated by Django 3.2.9 on 2022-01-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220104_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='author',
        ),
    ]
